version: "3.9"

services:
  aiogram-bot:
    build: .
    container_name: aiogram_bot
    restart: always
    env_file:
      - .dockerenv
    networks:
      - botnet
    depends_on:
      - mongodb
    volumes:
      - ./logs:/app/logs  
    command: ["uv", "run", "main.py"]

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: database
    restart: always
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGODB_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_logs:/var/log/mongodb
    networks:
      - botnet

networks:
  botnet:
    driver: bridge

volumes:
  mongo_data:
  mongo_logs:
