services:
  backend:
    build: ./backend_app
    container_name: backend
    restart: always
    ports:
      - "8000:8000" # backend API
    env_file:
      - ./backend_app/.env
    depends_on:
      - redis
      - db

  bot:
    build: ./bot_app
    container_name: bot
    restart: always
    ports:
      - "10000:10000" # bot service (polling)
    env_file:
      - ./bot_app/.env
    depends_on:
      - backend

  celery:
    build: ./backend_app
    container_name: celery
    command: celery -A src.core.celery_app worker -l info --concurrency=4
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    restart: always
    depends_on:
      - backend
      - redis
      - db

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: aiogram
      POSTGRES_USER: equalyzai
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data:
